### ISSUE TITLE
Question: Is there a way to get the rest of your work?

### ISSUE THREAD

**Issue by ekoepplin** [longhowlam/I_LOVE_IKEA_SHINY_APP#1]
Hi, thx for sharing your work! Any chance to get the code gathering  product images  via R package Rvest or the part which trains the model on the 9000 images?

**Comment by longhowlam** [comment]
Hi hugeme

Sure it is also on my Git, I did not really made that clear enough.

Scraping code with Rvest:
[scraper](https://github.com/longhowlam/ikeaScraper)

and putting images through the VGG network
[ikeaimages](https://github.com/longhowlam/ikeaimages)

Cheers,
Longhow
